### ISSUE TITLE
Update is not happening

### ISSUE THREAD

**Issue by sjambunathan** [codeulike/SandboxBerry#7] opened 2020-01-06 07:13 UTC
Every time when I transfer the records from prod to sandbox, It is not getting updated instead It creates a new record every time. Can you help me fix this?

**Comment by codeulike** [comment] 2020-01-06 11:24
It can't do updates - a side effect of the way it juggles ids when transferring data.
There is a delete function somewhere in the menu which you can use to clear out what was transferred last time - be careful though.

**Comment by codeulike** [comment] 2020-10-20 21:32
By design

**Closed as completed by codeulike** 2020-10-20 21:32 UTC
